### ISSUE TITLE
Hey so I made a better version of the python2 trip finder

### ISSUE THREAD

**Issue by The-Soulless** [gentoomen/4chantoolbox#13]
I don't know if your account is still active but here's the code

[Tripcode.txt](https://github.com/gentoomen/4chantoolbox/files/1175000/Tripcode.txt)

**Comment by JohnAnthony** [comment]
Cool. How does it benchmark?

Happy to merge if you add it to the repo and submit a pull request.

**Comment by JohnAnthony** [comment]
Also,
>I don't know if your account is still active

LAMMJohnson still lives, and responds to issues within minutes.

**Comment by The-Soulless** [comment]
Sorry, I'm still working on it to make it better, e.g. de-globalising the "--slow", also how do I benchmark?

**Comment by The-Soulless** [comment]
Ok, so I got everything good and ready to go, I'm just waiting for a reply on how to benchmark. I also added more comments

**Comment by JohnAnthony** [comment]
An example of a benchmark might be something like this

```
ja@vecna ~/git/4chantoolbox/Python2 (git)-[master] % time python2 TripGenerator.py -n4 -r (?i)john
Finding 4 matches of:
(?i)john
FOUND tripcode: 25605 => FZBBJoHnFE
Generated 100000 tripcodes...
Generated 200000 tripcodes...
FOUND tripcode: 285645 => QgGPJOHNSY
Generated 300000 tripcodes...
Generated 400000 tripcodes...
FOUND tripcode: 462565 => w4jQJohNmU
Generated 500000 tripcodes...
Generated 600000 tripcodes...
Generated 700000 tripcodes...
Generated 800000 tripcodes...
FOUND tripcode: 827285 => nJohntZvUg
25605 hashes to #FZBBJoHnFE
285645 hashes to #QgGPJOHNSY
462565 hashes to #w4jQJohNmU
827285 hashes to #nJohntZvUg
python2 TripGenerator.py -n4 -r (?i)john  12.29s user 0.01s system 100% cpu 12.297 total
```

You might even want to compare the old and new versions.

**Comment by JohnAnthony** [comment]
Other than that, you should make a pull request. I've skimmed your code but it'd better to see a diff generated by a pull request.

**Comment by The-Soulless** [comment]
So, I did my own sorta makeshift benchmark, by putting "t = time.time()" at the beginning of main, and then putting "print time.time()-t" at the end and I found that the old version (Even without optimisation" is better than my version with optimisation. So I just figured I might as well just optimise your version :/

**Comment by The-Soulless** [comment]
Made a pull request
