### ISSUE TITLE
Inconsistent behavior in the C dupechecker when argv[1] is "." or "..", recursive flag enabled by default, and minor stuff

### ISSUE THREAD

**Issue by elirandayan** [gentoomen/4chantoolbox#16]
Couldn't let me open a pull request, so here it is.

**First issue**

I was rewriting this as an exercise and noticed the dupechecker doesn't accept "." and ".." as a valid location even though it should work. I'd expected it to work similar to other command line utilities.

To replicate

    cd /tmp
    git clone http://github.com/gentoomen/4chantoolbox
    cd 4chantoolbox/C/
    make
    
    touch junk trash	# remember to wash your hands
    file . .. junk trash	# should tell you it's a directory
    ./Dupechecker .		# no output
    ./Dupechecker ..	# same
    ./Dupechecker -r . ..	# nothing, again
    
    rm junk trash

**Second issue**

Recursion flag is enabled by default

    unsigned int recursive   = 1;       /* defaults to not recursive */
This just contradicts the comment.

**Minor issues**

There's also a few other minor issues, such as the message about the current dictionary being used is swallowed up if any match is found, and also the -r flag producing noise if it goes over a . directory. (try running it on the repo) and finally, the -h flag mentions python.

Thanks.

**Comment by elirandayan** [comment]
Thought it'll let me open a pull request, but w/e here's the diff/patch

    30c30
    < unsigned int recursive   = 0;       /* defaults to not recursive */
    ---
    > unsigned int recursive   = 1;       /* defaults to not recursive */
    216,223c216
    < 		if( !strcmp(".", argv[i]) || !strcmp("..", argv[i]) ) {
    < 		    workdir = malloc(strlen(argv[i]) + 1);
    < 		    if (!workdir)
    <                         errout("Failed to malloc workdir");
    < 		    sprintf(workdir, "%s/", argv[i]);
    < 	        }
    < 	         else
    <                     workdir = argv[i];
    ---
    >             workdir = argv[i];
    355a349
    > 

(first time doing this so I probably screwed something up)

**Comment by JohnAnthony** [comment]
Looks like you've changed default behaviour to recursive, here. The behaviour based upon `.` and `..` input is wrong, but I'm not usre this is a correct fix.

Also, as an aside, this tool is old and unmaintained; you should use fdupes instead.

**Comment by elirandayan** [comment]
A late reply but the reason I was looking at this old stuff was because I have fond memories of #/g/sicp and wanted to contribute back.

Anyways, hope you're doing well, LAMM.
